### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Mennaruuk** [johnjago/awesome-ad-free#11]
- **nomoreads.org** ([Wayback Machine](http://web.archive.org/web/20190121234844/https://nomoreads.org/))
- **voltra.co** (their page just shows their logo. [Voltra Premium, ](https://voltra.co/premium) [music server, ](https://voltra.co/musicserver) [feedback page, ](https://voltra.co/feedback)[blog, ](https://blog.voltra.co/) and [about us page](https://voltra.co/about) give a 404 error. Their [account page](https://account.voltra.co/) is broken. I can’t make a new account. Syncing with iTunes doesn’t grab music. Their support email no longer works.)
- **goblinrefuge.com** (still up but will shut down per announcement)
- **artnotads.org** ([Wayback Machine](http://web.archive.org/web/20190111233537/http://artnotads.org/))

I think these services should be in their own “no longer maintained” section instead of deleted, because there remains value for newcomers to know about these services even if they don’t/won’t work any longer, and they might inspire new and better ideas!

**Comment by johnjago** [comment]
This is a good idea. Thanks for cleaning up the broken links! I'll go ahead and merge the PR.
